### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by mallim** [chanwit/spock-report-html#11]
Compiled in JDK 1.6

Running in 

``` xml
            <plugin>
                <groupId>org.codehaus.gmaven</groupId>
                <artifactId>gmaven-plugin</artifactId>
                <version>1.5</version>
                <configuration>
                    <providerSelection>2.0</providerSelection>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.gmaven.runtime</groupId>
                        <artifactId>gmaven-runtime-2.0</artifactId>
                        <version>1.5</version>
                    </dependency>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-all</artifactId>
                        <version>1.5</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <goals>
                            <goal>generateStubs</goal>
                            <goal>compile</goal>
                            <goal>generateTestStubs</goal>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

And I am getting the error below:

``` java
java.lang.NullPointerException: null
    at java.text.MessageFormat.applyPattern(MessageFormat.java:436)
    at java.text.MessageFormat.<init>(MessageFormat.java:363)
    at java.text.MessageFormat.format(MessageFormat.java:835)
    at org.spockframework.extension.ReportExtension$1.fmt(ReportExtension.groovy:36)
    at org.spockframework.extension.ReportExtension$1.afterFeature(ReportExtension.groovy:167)
    at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:138)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

Did I miss something in my pom.xml?

**Comment by rustjson** [comment]
Hi @Chanwit remember me?

**Comment by chanwit** [comment]
Oh yes. @RustJason are you using this lib?

It's not actively maintained anyway.

**Comment by rustjson** [comment]
Just come by and say Hi. :) Hahaha
